SELECT
    CNX.CNX_FILIAL AS FILIAL,
    CNX.CNX_CONTRA AS CONTRATO,
    CN9.CN9_TPCTO AS TIPO_CONTRATO,
    CN1.CN1_DESCRI AS DESC_TIPO_CONTRATO,
    CNX.CNX_FORNEC AS FORNECEDOR,
    CNX.CNX_FORNEC AS COD_FORNECEDOR,
    CNX.CNX_LJFORN AS LOJA_FORNECEDOR,
    SA2.A2_NOME AS NOME_FORNECEDOR,
    SA2.A2_CGC AS CNPJ_FORNECEDOR,
    CNX.CNX_NUMERO AS NUMERO_ADIANTAMENTO,
    CNX.CNX_DTADT AS DATA_ADIANTAMENTO,
    CNX.CNX_VLADT AS VALOR_ADIANTAMENTO,
    CNX.CNX_SALDO AS SALDO_ADIANTAMENTO,
    CN9.CN9_VLATU AS VALOR_ATUAL_CONTRATO,
    CN9.CN9_SITUAC AS SITUACAO,
    CASE
        WHEN TRIM(CN9.CN9_SITUAC) = '05' THEN 'VIGENTE'
        WHEN TRIM(CN9.CN9_SITUAC) = '06' THEN 'PARALISADO'
        WHEN TRIM(CN9.CN9_SITUAC) = '01' THEN 'CANCELADO'
        WHEN TRIM(CN9.CN9_SITUAC) = '10' THEN 'REVISADO'
        WHEN TRIM(CN9.CN9_SITUAC) = '02' THEN 'ELABORACAO'
        WHEN TRIM(CN9.CN9_SITUAC) = '03' THEN 'EMITIDO'
        WHEN TRIM(CN9.CN9_SITUAC) = '04' THEN 'APROVACAO'
        WHEN TRIM(CN9.CN9_SITUAC) = '09' THEN 'REVISAO'
        WHEN TRIM(CN9.CN9_SITUAC) = '07' THEN 'SOLICITACAO_FINALIZACAO'
        WHEN TRIM(CN9.CN9_SITUAC) = '08' THEN 'FINALIZADO'
        ELSE 'NAO_INFORMADO'
    END AS STATUS_CONTRATO,
    CN9.CN9_DTINIC AS DATA_INICIO,
    CN9.CN9_DTFIM AS DATA_FINAL
FROM CNX010 CNX
LEFT JOIN CN9010 CN9
ON CN9.CN9_NUMERO = CNX.CNX_CONTRA
AND CN9.CN9_FILIAL = CNX.CNX_FILIAL
AND CN9.D_E_L_E_T_ = ' '
AND NOT EXISTS (SELECT 1 FROM CN9010 CN9B WHERE CN9B.CN9_NUMERO = CN9.CN9_NUMERO AND CN9B.CN9_FILIAL = CN9.CN9_FILIAL AND CN9B.D_E_L_E_T_ = ' ' AND (NVL(CN9B.CN9_DTULST, ' ') > NVL(CN9.CN9_DTULST, ' ') OR (NVL(CN9B.CN9_DTULST, ' ') = NVL(CN9.CN9_DTULST, ' ') AND CN9B.R_E_C_N_O_ > CN9.R_E_C_N_O_)))
LEFT JOIN CN1010 CN1
ON CN1.CN1_CODIGO = CN9.CN9_TPCTO
AND CN1.D_E_L_E_T_ = ' '
INNER JOIN SA2010 SA2
ON SA2.A2_COD = CNX.CNX_FORNEC
AND SA2.A2_LOJA = CNX.CNX_LJFORN
AND SA2.D_E_L_E_T_ = ' '
WHERE CNX.D_E_L_E_T_ = ' '