SELECT
    CNC.CNC_FILIAL AS FILIAL,
    CNC.CNC_NUMERO AS CONTRATO,
    CNC.CNC_REVISA AS REVISAO,
    CNC.CNC_CODIGO AS COD_FORNECEDOR,
    CASE WHEN TRIM(CNC.CNC_LOJA) IS NULL THEN '0000' ELSE CNC.CNC_LOJA END AS LOJA_FORNECEDOR,
    SA2.A2_NOME AS NOME_FORNECEDOR,
    SA2.A2_CGC AS CNPJ_FORNECEDOR,
    (
        SELECT COUNT(*)
        FROM CNC010 CNCQ
        WHERE CNCQ.CNC_FILIAL = CNC.CNC_FILIAL
        AND CNCQ.CNC_NUMERO = CNC.CNC_NUMERO
        AND CNCQ.CNC_REVISA = CNC.CNC_REVISA
        AND CNCQ.D_E_L_E_T_ = ' '
    ) AS QTD_FORNECEDORES_REVISAO,
    CASE
        WHEN (
            SELECT COUNT(*)
            FROM CNC010 CNCQ
            WHERE CNCQ.CNC_FILIAL = CNC.CNC_FILIAL
            AND CNCQ.CNC_NUMERO = CNC.CNC_NUMERO
            AND CNCQ.CNC_REVISA = CNC.CNC_REVISA
            AND CNCQ.D_E_L_E_T_ = ' '
        ) > 1 THEN 'SIM'
        ELSE 'NAO'
    END AS MULTIPLOS_FORNECEDORES
FROM CNC010 CNC
LEFT JOIN SA2010 SA2
ON SA2.A2_COD = CNC.CNC_CODIGO
AND SA2.D_E_L_E_T_ = ' '
AND SA2.A2_LOJA = CASE WHEN TRIM(CNC.CNC_LOJA) IS NULL THEN '0000' ELSE CNC.CNC_LOJA END
WHERE CNC.D_E_L_E_T_ = ' '
AND NOT EXISTS (
    SELECT 1
    FROM CNC010 CNCB
    WHERE CNCB.CNC_FILIAL = CNC.CNC_FILIAL
    AND CNCB.CNC_NUMERO = CNC.CNC_NUMERO
    AND CNCB.CNC_REVISA = CNC.CNC_REVISA
    AND CNCB.D_E_L_E_T_ = ' '
    AND (
        (TRIM(CNC.CNC_CODIGO) IS NULL AND TRIM(CNCB.CNC_CODIGO) IS NOT NULL)
        OR (
            (
                (TRIM(CNC.CNC_CODIGO) IS NULL AND TRIM(CNCB.CNC_CODIGO) IS NULL)
                OR (TRIM(CNC.CNC_CODIGO) IS NOT NULL AND TRIM(CNCB.CNC_CODIGO) IS NOT NULL)
            )
            AND CNCB.R_E_C_N_O_ > CNC.R_E_C_N_O_
        )
    )
)