SELECT
    CN9.CN9_FILIAL AS FILIAL,
    CN9.CN9_NUMERO AS CONTRATO,
    CNC.CNC_CODIGO AS COD_FORNECEDOR,
    CASE WHEN TRIM(CNC.CNC_LOJA) IS NULL THEN '0000' ELSE CNC.CNC_LOJA END AS LOJA_FORNECEDOR,
    SA2.A2_NOME AS NOME_FORNECEDOR,
    SA2.A2_CGC AS CNPJ_FORNECEDOR,
    CN9.CN9_TPCTO AS TIPO_CONTRATO,
    CN1.CN1_DESCRI AS DESCRICAO_TIPO_CONTRATO,
    CN9.CN9_DESCRI AS DESCRICAO,
    CN9.CN9_SITUAC AS SITUACAO,
    CASE
        WHEN TRIM(CN9.CN9_SITUAC) = '05' THEN 'VIGENTE'
        WHEN TRIM(CN9.CN9_SITUAC) = '06' THEN 'PARALISADO'
        WHEN TRIM(CN9.CN9_SITUAC) = '01' THEN 'CANCELADO'
        WHEN TRIM(CN9.CN9_SITUAC) = '10' THEN 'REVISADO'
        WHEN TRIM(CN9.CN9_SITUAC) = '02' THEN 'ELABORACAO'
        WHEN TRIM(CN9.CN9_SITUAC) = '03' THEN 'EMITIDO'
        WHEN TRIM(CN9.CN9_SITUAC) = '04' THEN 'APROVACAO'
        WHEN TRIM(CN9.CN9_SITUAC) = '09' THEN 'REVISAO'
        WHEN TRIM(CN9.CN9_SITUAC) = '07' THEN 'SOLICITACAO_FINALIZACAO'
        WHEN TRIM(CN9.CN9_SITUAC) = '08' THEN 'FINALIZADO'
        ELSE 'NAO_INFORMADO'
    END AS STATUS_CONTRATO,
    CN9.CN9_DTINIC AS DATA_INICIO,
    CN9.CN9_ASSINA AS DATA_ASSINATURA,
    CN9.CN9_DTFIM AS DATA_FINAL,
    CN9.CN9_DTULST AS DATA_ULTIMO_STATUS,
    CN9.CN9_CONDPG AS CONDICAO_PAGAMENTO,
    SE4.E4_DESCRI AS DESCRICAO_CONDICAO_PAGAMENTO,
    CN9.CN9_VIGE AS VIGENCIA,
    CN9.CN9_UNVIGE AS UNIDADE_VIGENCIA,
    ' ' AS REVISAO,
    CN9.CN9_VLINI AS VALOR_INICIAL,
    CN9.CN9_VLATU AS VALOR_ATUAL,
    CN9.CN9_SALDO AS SALDO_CONTRATO,
    CN9.CN9_NUMERO AS CN9_NUMERO,
    CN9.CN9_DTFIM AS CN9_DTFIM,
    CN9.CN9_SITUAC AS CN9_SITUAC
FROM CN9010 CN9
LEFT JOIN CN1010 CN1
ON CN1.CN1_CODIGO = CN9.CN9_TPCTO
AND CN1.D_E_L_E_T_ = ' '
LEFT JOIN SE4010 SE4
ON SE4.E4_CODIGO = CN9.CN9_CONDPG
AND SE4.D_E_L_E_T_ = ' '
INNER JOIN CNC010 CNC
ON CNC.CNC_NUMERO = CN9.CN9_NUMERO
AND CNC.CNC_FILIAL = CN9.CN9_FILIAL
AND CNC.CNC_REVISA = CN9.CN9_REVISA
AND CNC.D_E_L_E_T_ = ' '
AND NOT EXISTS (SELECT 1 FROM CNC010 CNCB WHERE CNCB.CNC_FILIAL = CNC.CNC_FILIAL AND CNCB.CNC_NUMERO = CNC.CNC_NUMERO AND CNCB.CNC_REVISA = CNC.CNC_REVISA AND CNCB.D_E_L_E_T_ = ' ' AND ((TRIM(CNC.CNC_CODIGO) IS NULL AND TRIM(CNCB.CNC_CODIGO) IS NOT NULL) OR (((TRIM(CNC.CNC_CODIGO) IS NULL AND TRIM(CNCB.CNC_CODIGO) IS NULL) OR (TRIM(CNC.CNC_CODIGO) IS NOT NULL AND TRIM(CNCB.CNC_CODIGO) IS NOT NULL)) AND CNCB.R_E_C_N_O_ < CNC.R_E_C_N_O_)))
LEFT JOIN SA2010 SA2
ON SA2.A2_COD = CNC.CNC_CODIGO
AND SA2.D_E_L_E_T_ = ' '
AND SA2.A2_LOJA = CASE WHEN TRIM(CNC.CNC_LOJA) IS NULL THEN '0000' ELSE CNC.CNC_LOJA END
WHERE CN9.D_E_L_E_T_ = ' '
AND TRIM(CN9.CN9_SITUAC) <> '10'
