SELECT
    CN9.CN9_FILIAL AS FILIAL,
    CN9.CN9_NUMERO AS CONTRATO,
    CNC.CNC_CODIGO AS COD_FORNECEDOR,
    CASE WHEN TRIM(CNC.CNC_LOJA) IS NULL THEN '0000' ELSE CNC.CNC_LOJA END AS LOJA_FORNECEDOR,
    SA2.A2_NOME AS NOME_FORNECEDOR,
    SA2.A2_CGC AS CNPJ_FORNECEDOR,
    CN9.CN9_TPCTO AS TIPO_CONTRATO,
    CN1.CN1_DESCRI AS DESC_TIPO_CONTRATO,
    CN9.CN9_SITUAC AS SITUACAO,
    CASE
        WHEN TRIM(CN9.CN9_SITUAC) = '05' THEN 'VIGENTE'
        WHEN TRIM(CN9.CN9_SITUAC) = '06' THEN 'PARALISADO'
        WHEN TRIM(CN9.CN9_SITUAC) = '01' THEN 'CANCELADO'
        WHEN TRIM(CN9.CN9_SITUAC) = '10' THEN 'REVISADO'
        WHEN TRIM(CN9.CN9_SITUAC) = '02' THEN 'ELABORACAO'
        WHEN TRIM(CN9.CN9_SITUAC) = '03' THEN 'EMITIDO'
        WHEN TRIM(CN9.CN9_SITUAC) = '04' THEN 'APROVACAO'
        WHEN TRIM(CN9.CN9_SITUAC) = '09' THEN 'REVISAO'
        WHEN TRIM(CN9.CN9_SITUAC) = '07' THEN 'SOLICITACAO_FINALIZACAO'
        WHEN TRIM(CN9.CN9_SITUAC) = '08' THEN 'FINALIZADO'
        ELSE 'NAO_INFORMADO'
    END AS STATUS_CONTRATO,
    CN9.CN9_VLATU AS VALOR_CONTRATO,
    (
        SELECT COUNT(DISTINCT CNF.CNF_PARCEL)
        FROM CNF010 CNF
        WHERE CNF.CNF_CONTRA = CN9.CN9_NUMERO
        AND CNF.CNF_FILIAL = CN9.CN9_FILIAL
        AND CNF.CNF_REVISA = CN9.CN9_REVISA
        AND CNF.D_E_L_E_T_ = ' '
    ) AS QTD_PARCELAS,
    (
        SELECT NVL(SUM(CNF.CNF_VLPREV), 0)
        FROM CNF010 CNF
        WHERE CNF.CNF_CONTRA = CN9.CN9_NUMERO
        AND CNF.CNF_FILIAL = CN9.CN9_FILIAL
        AND CNF.CNF_REVISA = CN9.CN9_REVISA
        AND CNF.D_E_L_E_T_ = ' '
    ) AS VALOR_PREVISTO,
    (
        SELECT NVL(SUM(CNF.CNF_VLREAL), 0)
        FROM CNF010 CNF
        WHERE CNF.CNF_CONTRA = CN9.CN9_NUMERO
        AND CNF.CNF_FILIAL = CN9.CN9_FILIAL
        AND CNF.CNF_REVISA = CN9.CN9_REVISA
        AND CNF.D_E_L_E_T_ = ' '
    ) AS VALOR_REALIZADO,
    (
        SELECT NVL(SUM(CNF.CNF_SALDO), 0)
        FROM CNF010 CNF
        WHERE CNF.CNF_CONTRA = CN9.CN9_NUMERO
        AND CNF.CNF_FILIAL = CN9.CN9_FILIAL
        AND CNF.CNF_REVISA = CN9.CN9_REVISA
        AND CNF.D_E_L_E_T_ = ' '
    ) AS SALDO_FINANCEIRO,
    (
        SELECT COUNT(DISTINCT CASE WHEN CNF.CNF_DTVENC < CNF.CNF_DTREAL THEN CNF.CNF_PARCEL END)
        FROM CNF010 CNF
        WHERE CNF.CNF_CONTRA = CN9.CN9_NUMERO
        AND CNF.CNF_FILIAL = CN9.CN9_FILIAL
        AND CNF.CNF_REVISA = CN9.CN9_REVISA
        AND CNF.D_E_L_E_T_ = ' '
    ) AS PARCELAS_ATRASADAS,
    (
        SELECT NVL(SUM(CNX.CNX_VLADT), 0)
        FROM CNX010 CNX
        WHERE CNX.CNX_CONTRA = CN9.CN9_NUMERO
        AND CNX.CNX_FILIAL = CN9.CN9_FILIAL
        AND CNX.D_E_L_E_T_ = ' '
    ) AS VALOR_ADIANTADO,
    (
        SELECT NVL(SUM(CNX.CNX_SALDO), 0)
        FROM CNX010 CNX
        WHERE CNX.CNX_CONTRA = CN9.CN9_NUMERO
        AND CNX.CNX_FILIAL = CN9.CN9_FILIAL
        AND CNX.D_E_L_E_T_ = ' '
    ) AS SALDO_ADIANTAMENTO,
    CASE
        WHEN (
            SELECT NVL(SUM(CNF.CNF_VLPREV), 0)
            FROM CNF010 CNF
            WHERE CNF.CNF_CONTRA = CN9.CN9_NUMERO
            AND CNF.CNF_FILIAL = CN9.CN9_FILIAL
            AND CNF.CNF_REVISA = CN9.CN9_REVISA
            AND CNF.D_E_L_E_T_ = ' '
        ) > 0 THEN
            (
                (
                    SELECT NVL(SUM(CNF.CNF_VLREAL), 0)
                    FROM CNF010 CNF
                    WHERE CNF.CNF_CONTRA = CN9.CN9_NUMERO
                    AND CNF.CNF_FILIAL = CN9.CN9_FILIAL
                    AND CNF.CNF_REVISA = CN9.CN9_REVISA
                    AND CNF.D_E_L_E_T_ = ' '
                ) /
                (
                    SELECT NVL(SUM(CNF.CNF_VLPREV), 0)
                    FROM CNF010 CNF
                    WHERE CNF.CNF_CONTRA = CN9.CN9_NUMERO
                    AND CNF.CNF_FILIAL = CN9.CN9_FILIAL
                    AND CNF.CNF_REVISA = CN9.CN9_REVISA
                    AND CNF.D_E_L_E_T_ = ' '
                )
            ) * 100
        ELSE 0
    END AS PERCENTUAL_REALIZADO
FROM CN9010 CN9
LEFT JOIN CN1010 CN1
ON CN1.CN1_CODIGO = CN9.CN9_TPCTO
AND CN1.D_E_L_E_T_ = ' '
INNER JOIN CNC010 CNC
ON CNC.CNC_NUMERO = CN9.CN9_NUMERO
AND CNC.CNC_FILIAL = CN9.CN9_FILIAL
AND CNC.CNC_REVISA = CN9.CN9_REVISA
AND CNC.D_E_L_E_T_ = ' '
AND NOT EXISTS (SELECT 1 FROM CNC010 CNCB WHERE CNCB.CNC_FILIAL = CNC.CNC_FILIAL AND CNCB.CNC_NUMERO = CNC.CNC_NUMERO AND CNCB.CNC_REVISA = CNC.CNC_REVISA AND CNCB.D_E_L_E_T_ = ' ' AND ((TRIM(CNC.CNC_CODIGO) IS NULL AND TRIM(CNCB.CNC_CODIGO) IS NOT NULL) OR (((TRIM(CNC.CNC_CODIGO) IS NULL AND TRIM(CNCB.CNC_CODIGO) IS NULL) OR (TRIM(CNC.CNC_CODIGO) IS NOT NULL AND TRIM(CNCB.CNC_CODIGO) IS NOT NULL)) AND CNCB.R_E_C_N_O_ > CNC.R_E_C_N_O_)))
LEFT JOIN SA2010 SA2
ON SA2.A2_COD = CNC.CNC_CODIGO
AND SA2.D_E_L_E_T_ = ' '
AND SA2.A2_LOJA = CASE WHEN TRIM(CNC.CNC_LOJA) IS NULL THEN '0000' ELSE CNC.CNC_LOJA END
WHERE CN9.D_E_L_E_T_ = ' '
AND NOT EXISTS (SELECT 1 FROM CN9010 CN9B WHERE CN9B.CN9_NUMERO = CN9.CN9_NUMERO AND CN9B.CN9_FILIAL = CN9.CN9_FILIAL AND CN9B.D_E_L_E_T_ = ' ' AND (NVL(CN9B.CN9_DTULST, ' ') > NVL(CN9.CN9_DTULST, ' ') OR (NVL(CN9B.CN9_DTULST, ' ') = NVL(CN9.CN9_DTULST, ' ') AND CN9B.R_E_C_N_O_ > CN9.R_E_C_N_O_)))

