SELECT
    CNF.CNF_FILIAL AS FILIAL,
    CNF.CNF_CONTRA AS CONTRATO,
    CNC.CNC_CODIGO AS COD_FORNECEDOR,
    CASE WHEN TRIM(CNC.CNC_LOJA) IS NULL THEN '0000' ELSE CNC.CNC_LOJA END AS LOJA_FORNECEDOR,
    SA2.A2_NOME AS NOME_FORNECEDOR,
    SA2.A2_CGC AS CNPJ_FORNECEDOR,
    CN9.CN9_TPCTO AS TIPO_CONTRATO,
    CN1.CN1_DESCRI AS DESC_TIPO_CONTRATO,
    CNF.CNF_PARCEL AS PARCELA,
    CNF.CNF_COMPET AS COMPETENCIA,
    CNF.CNF_DTVENC AS DATA_VENCIMENTO,
    NVL(SUM(CNF.CNF_VLPREV), 0) AS VALOR_PREVISTO,
    NVL(SUM(CNF.CNF_VLREAL), 0) AS VALOR_REALIZADO,
    NVL(SUM(CNF.CNF_SALDO), 0) AS SALDO_FINANCEIRO
FROM CNF010 CNF
LEFT JOIN CN9010 CN9
ON CN9.CN9_NUMERO = CNF.CNF_CONTRA
AND CN9.CN9_FILIAL = CNF.CNF_FILIAL
AND CN9.CN9_REVISA = CNF.CNF_REVISA
AND CN9.D_E_L_E_T_ = ' '
AND NOT EXISTS (SELECT 1 FROM CN9010 CN9B WHERE CN9B.CN9_NUMERO = CN9.CN9_NUMERO AND CN9B.CN9_FILIAL = CN9.CN9_FILIAL AND CN9B.D_E_L_E_T_ = ' ' AND (NVL(CN9B.CN9_DTULST, ' ') > NVL(CN9.CN9_DTULST, ' ') OR (NVL(CN9B.CN9_DTULST, ' ') = NVL(CN9.CN9_DTULST, ' ') AND CN9B.R_E_C_N_O_ > CN9.R_E_C_N_O_)))
LEFT JOIN CN1010 CN1
ON CN1.CN1_CODIGO = CN9.CN9_TPCTO
AND CN1.D_E_L_E_T_ = ' '
INNER JOIN CNC010 CNC
ON CNC.CNC_NUMERO = CN9.CN9_NUMERO
AND CNC.CNC_FILIAL = CN9.CN9_FILIAL
AND CNC.CNC_REVISA = CN9.CN9_REVISA
AND CNC.D_E_L_E_T_ = ' '
AND NOT EXISTS (SELECT 1 FROM CNC010 CNCB WHERE CNCB.CNC_FILIAL = CNC.CNC_FILIAL AND CNCB.CNC_NUMERO = CNC.CNC_NUMERO AND CNCB.CNC_REVISA = CNC.CNC_REVISA AND CNCB.D_E_L_E_T_ = ' ' AND ((TRIM(CNC.CNC_CODIGO) IS NULL AND TRIM(CNCB.CNC_CODIGO) IS NOT NULL) OR (((TRIM(CNC.CNC_CODIGO) IS NULL AND TRIM(CNCB.CNC_CODIGO) IS NULL) OR (TRIM(CNC.CNC_CODIGO) IS NOT NULL AND TRIM(CNCB.CNC_CODIGO) IS NOT NULL)) AND CNCB.R_E_C_N_O_ > CNC.R_E_C_N_O_)))
LEFT JOIN SA2010 SA2
ON SA2.A2_COD = CNC.CNC_CODIGO
AND SA2.D_E_L_E_T_ = ' '
AND SA2.A2_LOJA = CASE WHEN TRIM(CNC.CNC_LOJA) IS NULL THEN '0000' ELSE CNC.CNC_LOJA END
WHERE CNF.D_E_L_E_T_ = ' '
GROUP BY
    CNF.CNF_FILIAL,
    CNF.CNF_CONTRA,
    CNC.CNC_CODIGO,
    CNC.CNC_LOJA,
    SA2.A2_NOME,
    SA2.A2_CGC,
    CN9.CN9_TPCTO,
    CN1.CN1_DESCRI,
    CNF.CNF_PARCEL,
    CNF.CNF_COMPET,
    CNF.CNF_DTVENC

