SELECT
    CN9.CN9_FILIAL AS FILIAL,
    CN9.CN9_NUMERO AS CONTRATO,

    CNC.CNC_CODIGO AS COD_FORNECEDOR,
    CASE
        WHEN TRIM(CNC.CNC_LOJA) IS NULL THEN '0000'
        ELSE CNC.CNC_LOJA
    END AS LOJA_FORNECEDOR,

    SA2.A2_NOME AS NOME_FORNECEDOR,
    SA2.A2_CGC AS CNPJ_FORNECEDOR,

    CN9.CN9_TPCTO AS TIPO_CONTRATO,
    CN1.CN1_DESCRI AS DESC_TIPO_CONTRATO,

    CN9.CN9_SITUAC AS SITUACAO_CONTRATO,

    CNA.CNA_NUMERO AS PLANILHA,
    CNA.CNA_TIPPLA AS TIPO_PLANILHA,
    CNL.CNL_DESCRI AS DESC_TIPO_PLANILHA,

    CNB.CNB_ITEM AS ITEM,
    CNB.CNB_PRODUT AS PRODUTO,
    CNB.CNB_DESCRI AS DESC_PRODUTO,
    CNB.CNB_UM AS UNIDADE,
    CNB.CNB_QUANT AS QUANTIDADE_CONTRATADA,
    CNB.CNB_QTDMED AS QUANTIDADE_MEDIDA,
    CNB.CNB_VLUNIT AS VALOR_UNITARIO,
    CNB.CNB_VLTOT AS VALOR_CONTRATADO,
    CNB.CNB_VLDESC AS DESCONTO

FROM CN9010 CN9

LEFT JOIN CNA010 CNA
       ON CNA.CNA_FILIAL = CN9.CN9_FILIAL
      AND CNA.CNA_CONTRA = CN9.CN9_NUMERO
      AND CNA.D_E_L_E_T_ = ' '

LEFT JOIN CNB010 CNB
       ON CNB.CNB_FILIAL = CNA.CNA_FILIAL
      AND CNB.CNB_CONTRA = CNA.CNA_CONTRA
      AND CNB.CNB_NUMERO = CNA.CNA_NUMERO
      AND CNB.D_E_L_E_T_ = ' '

LEFT JOIN CNL010 CNL
       ON CNL.CNL_CODIGO = CNA.CNA_TIPPLA
      AND CNL.D_E_L_E_T_ = ' '

LEFT JOIN CN1010 CN1
       ON CN1.CN1_CODIGO = CN9.CN9_TPCTO
      AND CN1.D_E_L_E_T_ = ' '

LEFT JOIN CNC010 CNC
       ON CNC.CNC_NUMERO = CN9.CN9_NUMERO
      AND CNC.CNC_FILIAL = CN9.CN9_FILIAL
      AND CNC.CNC_REVISA = CN9.CN9_REVISA
      AND CNC.D_E_L_E_T_ = ' '
      AND NOT EXISTS (
            SELECT 1
            FROM CNC010 CNCB
            WHERE CNCB.CNC_FILIAL = CNC.CNC_FILIAL
              AND CNCB.CNC_NUMERO = CNC.CNC_NUMERO
              AND CNCB.CNC_REVISA = CNC.CNC_REVISA
              AND CNCB.D_E_L_E_T_ = ' '
              AND (
                     (TRIM(CNC.CNC_CODIGO) IS NULL
                      AND TRIM(CNCB.CNC_CODIGO) IS NOT NULL)
                  OR (
                        (
                            (TRIM(CNC.CNC_CODIGO) IS NULL
                             AND TRIM(CNCB.CNC_CODIGO) IS NULL)
                         OR (TRIM(CNC.CNC_CODIGO) IS NOT NULL
                             AND TRIM(CNCB.CNC_CODIGO) IS NOT NULL)
                        )
                        AND CNCB.R_E_C_N_O_ > CNC.R_E_C_N_O_
                     )
              )
      )

LEFT JOIN SA2010 SA2
       ON SA2.A2_COD = CNC.CNC_CODIGO
      AND SA2.A2_LOJA =
            CASE
                WHEN TRIM(CNC.CNC_LOJA) IS NULL
                THEN '0000'
                ELSE CNC.CNC_LOJA
            END
      AND SA2.D_E_L_E_T_ = ' '

WHERE CN9.D_E_L_E_T_ = ' '

AND CNA.CNA_NUMERO IS NOT NULL

AND NOT EXISTS (
    SELECT 1
    FROM CN9010 CN9B
    WHERE CN9B.CN9_FILIAL = CN9.CN9_FILIAL
      AND CN9B.CN9_NUMERO = CN9.CN9_NUMERO
      AND CN9B.D_E_L_E_T_ = ' '
      AND (
            NVL(CN9B.CN9_DTULST,' ') > NVL(CN9.CN9_DTULST,' ')
         OR (
                NVL(CN9B.CN9_DTULST,' ') = NVL(CN9.CN9_DTULST,' ')
            AND CN9B.R_E_C_N_O_ > CN9.R_E_C_N_O_
            )
      )
)

AND NOT EXISTS (
    SELECT 1
    FROM CNA010 CNAX
    WHERE CNAX.CNA_FILIAL = CNA.CNA_FILIAL
      AND CNAX.CNA_CONTRA = CNA.CNA_CONTRA
      AND CNAX.CNA_NUMERO = CNA.CNA_NUMERO
      AND CNAX.D_E_L_E_T_ = ' '
      AND CNAX.R_E_C_N_O_ > CNA.R_E_C_N_O_
)

AND (
        CNB.R_E_C_N_O_ IS NULL
     OR NOT EXISTS (
            SELECT 1
            FROM CNB010 CNBX
            WHERE CNBX.CNB_FILIAL = CNB.CNB_FILIAL
              AND CNBX.CNB_CONTRA = CNB.CNB_CONTRA
              AND CNBX.CNB_NUMERO = CNB.CNB_NUMERO
              AND CNBX.CNB_ITEM = CNB.CNB_ITEM
              AND CNBX.D_E_L_E_T_ = ' '
              AND CNBX.R_E_C_N_O_ > CNB.R_E_C_N_O_
     )
)

ORDER BY
    CN9.CN9_FILIAL,
    CN9.CN9_NUMERO,
    CNA.CNA_NUMERO,
    CNB.CNB_ITEM;