SELECT
    CNE_FILIAL AS FILIAL,
    CNE_CONTRA AS CONTRATO,
    CNE_REVISA AS REVISAO_CONTRATO,
    CNE_NUMMED AS NUMERO_MEDICAO,
    COUNT(*) AS QTD_ITENS,
    COUNT(DISTINCT CNE_PRODUT) AS QTD_PRODUTOS_DISTINTOS,
    NVL(SUM(CNE_QTDSOL), 0) AS QTD_SOLICITADA,
    NVL(SUM(CNE_QUANT), 0) AS QTD_MEDIDA,
    NVL(SUM(CNE_VLTOT), 0) AS TOTAL_ITENS,
    NVL(SUM(CNE_VLLIQD), 0) AS TOTAL_LIQUIDO_ITENS,
    NVL(SUM(CNE_MULTA), 0) AS TOTAL_MULTAS_ITENS,
    NVL(SUM(CNE_BONIF), 0) AS TOTAL_BONIFICACOES_ITENS
FROM CNE010
WHERE D_E_L_E_T_ = ' '
GROUP BY
    CNE_FILIAL,
    CNE_CONTRA,
    CNE_REVISA,
    CNE_NUMMED
ORDER BY
    CNE_FILIAL,
    CNE_CONTRA,
    CNE_REVISA,
    CNE_NUMMED
