SELECT
    CNE_FILIAL AS FILIAL,
    CNE_CONTRA AS CONTRATO,
    CNE_REVISA AS REVISAO_CONTRATO,
    CNE_NUMMED AS NUMERO_MEDICAO,
    CNE_ITEM AS ITEM,
    CNE_PRODUT AS PRODUTO,
    CNE_QTDSOL AS QTD_SOLICITADA_ITEM,
    CNE_QUANT AS QTD_MEDIDA_ITEM,
    CNE_VLTOT AS VALOR_TOTAL_ITEM,
    CNE_VLLIQD AS VALOR_LIQUIDO_ITEM,
    CNE_MULTA AS VALOR_MULTA_ITEM,
    CNE_BONIF AS VALOR_BONIFICACAO_ITEM
FROM CNE010
WHERE D_E_L_E_T_ = ' '
ORDER BY
    CNE_FILIAL,
    CNE_CONTRA,
    CNE_REVISA,
    CNE_NUMMED,
    CNE_ITEM