-- BI Contratos - Medições
-- Tabela principal: CND010 (Cabeçalho das Medições)
-- Todos os indicadores da CNE010 sao calculados por subconsultas correlacionadas,
-- preservando compatibilidade com TOTVS Protheus/ChangeQuery.
-- A consulta retorna uma unica linha por medicao (CND_NUMMED).
-- Relacionamentos: CN9010 (Contrato), CNC010 (Fornecedor), SA2010 (Fornecedor), CN1010 (Tipo do Contrato)

SELECT
  CND.CND_FILIAL AS FILIAL,
    CND.CND_CONTRA AS CONTRATO,
    CND.CND_REVISA AS REVISAO_CONTRATO,

    CNC.CNC_CODIGO AS COD_FORNECEDOR,
    CASE
        WHEN TRIM(CNC.CNC_LOJA) IS NULL THEN '0000'
        ELSE CNC.CNC_LOJA
    END AS LOJA_FORNECEDOR,

    SA2.A2_NOME  AS NOME_FORNECEDOR,
    SA2.A2_CGC   AS CNPJ_FORNECEDOR,

    CN9.CN9_TPCTO AS TIPO_CONTRATO,
    CN1.CN1_DESCRI AS DESC_TIPO_CONTRATO,
    CN9.CN9_SITUAC AS SITUACAO,
    CN9.CN9_VLATU AS VALOR_ATUAL,

    CND.CND_NUMMED  AS NUMERO_MEDICAO,
    CND.CND_NUMERO  AS NUMERO_PLANILHA,
    CND.CND_COMPET  AS COMPETENCIA,

    CND.CND_DATAIN  AS DATA_INICIO,
    CND.CND_DATAFI  AS DATA_FIM,
    CND.CND_DTFIM   AS DATA_ENCERRAMENTO,
    CND.CND_DTVENC  AS DATA_VENCIMENTO,

    CND.CND_SITUAC  AS STATUS_MEDICAO,
    CASE
        WHEN TRIM(CND.CND_SITUAC) = '01' THEN 'CANCELADA'
        WHEN TRIM(CND.CND_SITUAC) = '02' THEN 'ELABORACAO'
        WHEN TRIM(CND.CND_SITUAC) = '03' THEN 'APROVADA'
        WHEN TRIM(CND.CND_SITUAC) = '04' THEN 'PAGA'
        WHEN TRIM(CND.CND_SITUAC) = '05' THEN 'ENCERRADA'
        WHEN TRIM(CND.CND_SITUAC) = '06' THEN 'LIBERADA'
        WHEN TRIM(CND.CND_SITUAC) = '07' THEN 'REPROVADA'
        ELSE 'NAO_INFORMADO'
    END AS STATUS_MEDICAO_DESC,

    CND.CND_VLPREV  AS VALOR_PREVISTO,
    CND.CND_VLTOT   AS VALOR_TOTAL_MEDICAO,
    CND.CND_VLLIQD  AS VALOR_LIQUIDO,
    CND.CND_TOTADT  AS VALOR_ADIANTAMENTO,
    CND.CND_RETCAC  AS VALOR_CAUCAO,
    CND.CND_VLMULT  AS VALOR_MULTAS,
    CND.CND_VLBONI  AS VALOR_BONIFICACOES,
    CND.CND_VLSALD  AS SALDO_MEDICAO,

    (
        SELECT COUNT(*)
        FROM CNE010 CNE
        WHERE CNE.CNE_FILIAL = CND.CND_FILIAL
          AND CNE.CNE_CONTRA = CND.CND_CONTRA
                    AND CNE.CNE_REVISA = CND.CND_REVISA
          AND CNE.CNE_NUMMED = CND.CND_NUMMED
          AND CNE.D_E_L_E_T_ = ' '
    ) AS QTD_ITENS,

    (
        SELECT COUNT(DISTINCT CNE.CNE_PRODUT)
        FROM CNE010 CNE
        WHERE CNE.CNE_FILIAL = CND.CND_FILIAL
          AND CNE.CNE_CONTRA = CND.CND_CONTRA
                    AND CNE.CNE_REVISA = CND.CND_REVISA
          AND CNE.CNE_NUMMED = CND.CND_NUMMED
          AND CNE.D_E_L_E_T_ = ' '
    ) AS QTD_PRODUTOS_DISTINTOS,

    (
        SELECT NVL(SUM(CNE.CNE_QTDSOL), 0)
        FROM CNE010 CNE
        WHERE CNE.CNE_FILIAL = CND.CND_FILIAL
          AND CNE.CNE_CONTRA = CND.CND_CONTRA
                    AND CNE.CNE_REVISA = CND.CND_REVISA
          AND CNE.CNE_NUMMED = CND.CND_NUMMED
          AND CNE.D_E_L_E_T_ = ' '
    ) AS QTD_SOLICITADA,

    (
        SELECT NVL(SUM(CNE.CNE_QUANT), 0)
        FROM CNE010 CNE
        WHERE CNE.CNE_FILIAL = CND.CND_FILIAL
          AND CNE.CNE_CONTRA = CND.CND_CONTRA
                    AND CNE.CNE_REVISA = CND.CND_REVISA
          AND CNE.CNE_NUMMED = CND.CND_NUMMED
          AND CNE.D_E_L_E_T_ = ' '
    ) AS QTD_MEDIDA,

    (
        SELECT NVL(SUM(CNE.CNE_VLTOT), 0)
        FROM CNE010 CNE
        WHERE CNE.CNE_FILIAL = CND.CND_FILIAL
          AND CNE.CNE_CONTRA = CND.CND_CONTRA
                    AND CNE.CNE_REVISA = CND.CND_REVISA
          AND CNE.CNE_NUMMED = CND.CND_NUMMED
          AND CNE.D_E_L_E_T_ = ' '
    ) AS TOTAL_ITENS,

    (
        SELECT NVL(SUM(CNE.CNE_VLLIQD), 0)
        FROM CNE010 CNE
        WHERE CNE.CNE_FILIAL = CND.CND_FILIAL
          AND CNE.CNE_CONTRA = CND.CND_CONTRA
                    AND CNE.CNE_REVISA = CND.CND_REVISA
          AND CNE.CNE_NUMMED = CND.CND_NUMMED
          AND CNE.D_E_L_E_T_ = ' '
    ) AS TOTAL_LIQUIDO_ITENS,

    (
        SELECT NVL(SUM(CNE.CNE_MULTA), 0)
        FROM CNE010 CNE
        WHERE CNE.CNE_FILIAL = CND.CND_FILIAL
          AND CNE.CNE_CONTRA = CND.CND_CONTRA
                    AND CNE.CNE_REVISA = CND.CND_REVISA
          AND CNE.CNE_NUMMED = CND.CND_NUMMED
          AND CNE.D_E_L_E_T_ = ' '
    ) AS TOTAL_MULTAS_ITENS,

    (
        SELECT NVL(SUM(CNE.CNE_BONIF), 0)
        FROM CNE010 CNE
        WHERE CNE.CNE_FILIAL = CND.CND_FILIAL
          AND CNE.CNE_CONTRA = CND.CND_CONTRA
                    AND CNE.CNE_REVISA = CND.CND_REVISA
          AND CNE.CNE_NUMMED = CND.CND_NUMMED
          AND CNE.D_E_L_E_T_ = ' '
    ) AS TOTAL_BONIFICACOES_ITENS

FROM CND010 CND

LEFT JOIN CN9010 CN9
       ON CN9.CN9_NUMERO = CND.CND_CONTRA
      AND CN9.CN9_FILIAL = CND.CND_FILIAL
    AND CN9.CN9_REVISA = CND.CND_REVISA
      AND CN9.D_E_L_E_T_ = ' '

LEFT JOIN CNC010 CNC
     ON CNC.CNC_NUMERO = CND.CND_CONTRA
    AND CNC.CNC_FILIAL = CND.CND_FILIAL
    AND CNC.CNC_REVISA = CND.CND_REVISA
      AND CNC.D_E_L_E_T_ = ' '

LEFT JOIN SA2010 SA2
       ON SA2.A2_COD = CNC.CNC_CODIGO
      AND SA2.A2_LOJA =
            CASE
                WHEN TRIM(CNC.CNC_LOJA) IS NULL
                THEN '0000'
                ELSE CNC.CNC_LOJA
            END
      AND SA2.D_E_L_E_T_ = ' '

LEFT JOIN CN1010 CN1
       ON CN1.CN1_CODIGO = CN9.CN9_TPCTO
      AND CN1.D_E_L_E_T_ = ' '

WHERE CND.D_E_L_E_T_ = ' '

ORDER BY
    CND.CND_FILIAL,
    CND.CND_CONTRA,
  CND.CND_REVISA,
    CND.CND_NUMMED;
