SELECT
    CND.CND_FILIAL AS FILIAL,
    CND.CND_CONTRA AS CONTRATO,
    CND.CND_REVISA AS REVISAO_CONTRATO,

    CNC.CNC_CODIGO AS COD_FORNECEDOR,
    CASE
        WHEN TRIM(CNC.CNC_LOJA) IS NULL THEN '0000'
        ELSE CNC.CNC_LOJA
    END AS LOJA_FORNECEDOR,

    SA2.A2_NOME  AS NOME_FORNECEDOR,
    SA2.A2_CGC   AS CNPJ_FORNECEDOR,

    CN9.CN9_TPCTO AS TIPO_CONTRATO,
    CN1.CN1_DESCRI AS DESC_TIPO_CONTRATO,
      CN9.CN9_SITUAC AS SITUACAO,
    CN9.CN9_VLATU AS VALOR_ATUAL,

    CND.CND_NUMMED  AS NUMERO_MEDICAO,
    CND.CND_NUMERO  AS NUMERO_PLANILHA,
    CND.CND_COMPET  AS COMPETENCIA,

    CND.CND_DATAIN  AS DATA_INICIO,
    CND.CND_DATAFI  AS DATA_FIM,
    CND.CND_DTFIM   AS DATA_ENCERRAMENTO,
    CND.CND_DTVENC  AS DATA_VENCIMENTO,

    CND.CND_SITUAC  AS STATUS_MEDICAO,

    CND.CND_VLPREV  AS VALOR_PREVISTO,
    CND.CND_VLTOT   AS VALOR_TOTAL_MEDICAO,
    CND.CND_VLLIQD  AS VALOR_LIQUIDO,
    CND.CND_TOTADT  AS VALOR_ADIANTAMENTO,
    CND.CND_RETCAC  AS VALOR_CAUCAO,
    CND.CND_VLMULT  AS VALOR_MULTAS,
    CND.CND_VLBONI  AS VALOR_BONIFICACOES,
    CND.CND_VLSALD  AS SALDO_MEDICAO

FROM CND010 CND

LEFT JOIN CN9010 CN9
       ON CN9.CN9_NUMERO = CND.CND_CONTRA
      AND CN9.CN9_FILIAL = CND.CND_FILIAL
            AND CN9.CN9_REVISA = CND.CND_REVISA
      AND CN9.D_E_L_E_T_ = ' '

LEFT JOIN CNC010 CNC
             ON CNC.CNC_NUMERO = CND.CND_CONTRA
            AND CNC.CNC_FILIAL = CND.CND_FILIAL
            AND CNC.CNC_REVISA = CND.CND_REVISA
      AND CNC.D_E_L_E_T_ = ' '

LEFT JOIN SA2010 SA2
       ON SA2.A2_COD = CNC.CNC_CODIGO
      AND SA2.A2_LOJA =
            CASE
                WHEN TRIM(CNC.CNC_LOJA) IS NULL
                THEN '0000'
                ELSE CNC.CNC_LOJA
            END
      AND SA2.D_E_L_E_T_ = ' '

LEFT JOIN CN1010 CN1
       ON CN1.CN1_CODIGO = CN9.CN9_TPCTO
      AND CN1.D_E_L_E_T_ = ' '

WHERE CND.D_E_L_E_T_ = ' '

ORDER BY
    CND.CND_FILIAL,
    CND.CND_CONTRA,
    CND.CND_REVISA,
    CND.CND_NUMMED
